# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Julia Schmidt-Lademann
description:      'The Data expert you have been looking for!'
url:              https://julia-schmidt-lademann.github.io/

author:
  name:           'Mark Otto'


# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/julia-schmidt-lademann/julia-schmidt-lademann.github.io
